import type { SiteContent } from '../../components/site-page';

export const ru: SiteContent = {
  locale: 'ru', nav: { works: 'Работы', about: 'Обо мне', contact: 'Контакт' }, identity: 'root@memasevich:~$ whoami', heroTitle: 'Я — MEMASEVICH.\nСИСАДМИН / DEVOPS\nРАЗРАБОТЧИК.', heroLead: 'Поднимаю и поддерживаю инфраструктуру, автоматизирую рутину, собираю собственные инструменты и делаю русские локализации сложных игр.', primaryCta: 'Смотреть работы', secondaryCta: 'Написать в Telegram',
  toolsTitle: 'Прикладная разработка', toolsIntro: 'Реальные внутренние решения из публичного GitHub-профиля. Код закрыт, поэтому здесь только подтверждённая задача и результат.',
  tools: [{ title: 'ЗАЩИТНИК ДЛЯ ТСД', type: 'ANDROID / INTERNAL', role: 'разработка приложения', task: 'Контролировать, находится ли складской ТСД в защитном чехле.', done: 'Приложение поднимает тревогу, если устройство вынули из чехла или оставили без присмотра.', status: 'внутренний проект / код закрыт', href: 'https://github.com/memasevich/memasevich', accent: 'violet' }, { title: 'МОДУЛЬ СКАНИРОВАНИЯ WMS', type: 'WMS / INTERNAL', role: 'разработка и замена модуля', task: 'Заменить устаревшее стороннее решение GS Code.', done: 'Модуль сканирования WMS переписан на собственное решение.', status: 'внутренний проект / код закрыт', href: 'https://github.com/memasevich/memasevich', accent: 'coral' }],
  localizationTitle: 'Игровые локализации', localizationIntro: 'Три публичных проекта из GitHub — с реальными изображениями, версиями и техническими деталями из README.',
  localizations: [{ title: 'Caves of Qud', area: 'C# / морфология / логи', description: 'Локализация для версии 2.0.211.x: более 165 000 строк, словари и паттерны, морфология, перевод интерфейса и сбор непереведённого текста.', status: 'репозиторий / v1.0.5', href: 'https://github.com/memasevich/CoQ-ru-translate-public', note: 'SOURCE: GITHUB / RussianLocalization/preview.png', image: '/projects/coq-localization.png', imageAlt: 'Русская локализация Caves of Qud — изображение из репозитория проекта' }, { title: 'R.E.P.O.', area: 'TSV / интерфейс / контент', description: 'Русификатор через встроенную систему локализации игры и три TSV-файла: Game, HUD и Menu. Переведены предметы, противники, обучение и интерфейс.', status: 'репозиторий / ~100%', href: 'https://github.com/memasevich/repo-russianlocalization', note: 'SOURCE: STEAM GUIDE / PUBLIC COVER', image: '/projects/repo-localization.jpg', imageAlt: 'Обложка публичного руководства по русской локализации R.E.P.O.' }, { title: 'Gnomoria', area: 'C# / XNA / перехват рендера', description: 'Dynamic Engine v0.6.0 перехватывает рендеринг XNA и выводит кириллицу без правки font texture/XNB. В словаре релиза — 12 253 записи.', status: 'репозиторий / v0.6.0', href: 'https://github.com/memasevich/Gnomoria-Russian-Translation', note: 'SOURCE: GITHUB / images/in_game_menu.png', image: '/projects/gnomoria-localization.png', imageAlt: 'Русское меню Gnomoria — скриншот из репозитория проекта' }],
  aboutTitle: 'Обо мне', aboutText: 'Memasevich — системный администратор, DevOps-специалист и независимый разработчик. Работаю с инфраструктурой, CI/CD и автоматизацией, делаю внутренние решения для складского оборудования и русские локализации сложных игр. Люблю системы, которые можно понять, запустить и поддерживать без магии.', contactEyebrow: 'Контакт', contactTitle: 'НА СВЯЗИ.\nПИШИ.', contactText: 'Можно написать про локализации, проекты, совместную работу или просто познакомиться.', contactActions: [{ label: 'Написать в Telegram', href: 'https://t.me/memasev1ch' }, { label: 'Открыть GitHub', href: 'https://github.com/memasevich' }, { label: 'Поддержать на Boosty', href: 'https://boosty.to/memasevich' }], footer: 'Русский — основная версия',
};
