import Link from 'next/link';

type Project = { title: string; description: string; tags: string[]; art: 'grid' | 'orb' | 'signal' };
export type SiteContent = {
  locale: 'ru' | 'en'; nav: { projects: string; approach: string; contact: string }; eyebrow: string; title: string; lede: string; note: string; projectsTitle: string; projects: Project[]; approachTitle: string; principles: { title: string; text: string }[]; contactEyebrow: string; contactTitle: string; contactCta: string; footer: string;
};

function ProjectArt({ type }: { type: Project['art'] }) {
  if (type === 'grid') return <svg viewBox="0 0 800 510" aria-label="Абстрактная сетка интерфейса" xmlns="http://www.w3.org/2000/svg"><rect width="800" height="510" fill="#d8ff45"/><path d="M0 120h800M0 240h800M0 360h800M160 0v510M320 0v510M480 0v510M640 0v510" stroke="#131315" strokeOpacity=".25"/><rect x="58" y="62" width="280" height="148" rx="12" fill="#131315"/><circle cx="88" cy="91" r="8" fill="#ff755f"/><rect x="84" y="268" width="490" height="118" rx="12" fill="#f4f2ed"/><path d="M110 330h260M110 350h190" stroke="#131315" strokeWidth="8" strokeLinecap="round"/><path d="m575 95 104 104-104 104-104-104z" fill="#a694ff" stroke="#131315" strokeWidth="5"/></svg>;
  if (type === 'orb') return <svg viewBox="0 0 800 510" aria-label="Абстрактный визуальный модуль" xmlns="http://www.w3.org/2000/svg"><rect width="800" height="510" fill="#131315"/><circle cx="420" cy="250" r="164" fill="#a694ff"/><circle cx="420" cy="250" r="104" fill="#ff755f"/><circle cx="420" cy="250" r="47" fill="#d8ff45"/><path d="M0 416c135-45 209 28 326-30 126-62 210 62 474-33" fill="none" stroke="#f4f2ed" strokeWidth="2"/><path d="M0 94c152 49 205-31 347 31 130 57 242-69 453 20" fill="none" stroke="#f4f2ed" strokeOpacity=".45" strokeWidth="2"/></svg>;
  return <svg viewBox="0 0 800 510" aria-label="Сигнальная диаграмма" xmlns="http://www.w3.org/2000/svg"><rect width="800" height="510" fill="#ff755f"/><path d="M0 380 100 295l100 31 100-164 100 92 100-176 100 68 100-91 100 34" fill="none" stroke="#131315" strokeWidth="12"/><path d="M0 420h800M0 62h800" stroke="#131315" strokeOpacity=".25" strokeWidth="2"/><circle cx="500" cy="254" r="19" fill="#d8ff45" stroke="#131315" strokeWidth="6"/><rect x="54" y="70" width="175" height="46" rx="23" fill="#131315"/><text x="82" y="99" fill="#f4f2ed" fontFamily="Arial" fontSize="16" fontWeight="700">LIVE / 03</text></svg>;
}

export default function SitePage({ content, locale }: { content: SiteContent; locale: 'ru' | 'en' }) {
  const isRussian = locale === 'ru';
  return <div className="site-shell">
    <header className="container topbar"><Link className="wordmark" href={isRussian ? '/' : '/en/'} aria-label="MEMASEVICH">MEMASEVICH</Link><nav aria-label={isRussian ? 'Основная навигация' : 'Main navigation'}><a className="nav-link" href="#projects">{content.nav.projects}</a><a className="nav-link" href="#approach">{content.nav.approach}</a><a className="nav-link" href="#contact">{content.nav.contact}</a><span className="locale-switch" aria-label={isRussian ? 'Язык сайта' : 'Site language'}><Link className={isRussian ? 'active' : ''} href="/">RU</Link><Link className={!isRussian ? 'active' : ''} href="/en/">EN</Link></span></nav></header>
    <main>
      <section className="container hero"><div className="hero-grid"><div><div className="eyebrow">{content.eyebrow}</div><h1>MEMASEVICH<span className="hero-mark">·</span></h1><p className="hero-lede">{content.lede}</p></div><div className="hero-note"><div className="eyebrow">01 — 03</div><p>{content.note}</p></div></div><div className="scroll-cue">{isRussian ? 'Смотреть проекты' : 'View projects'}</div></section>
      <section className="container band" id="projects"><div className="section-head"><h2>{content.projectsTitle}</h2><span className="section-index">{isRussian ? 'Избранное / 2026' : 'Selected / 2026'}</span></div><div className="projects">{content.projects.map(project => <article className="project-card" key={project.title}><div className="project-art"><ProjectArt type={project.art} /></div><div className="project-info"><h3>{project.title}</h3><p>{project.description}</p><div className="project-meta">{project.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="container principles" id="approach"><div><div className="eyebrow">02 — {isRussian ? 'Подход' : 'Approach'}</div><h2>{content.approachTitle}</h2></div><div className="principle-list">{content.principles.map((principle, index) => <div className="principle" key={principle.title}><span className="principle-number">0{index + 1}</span><div><h3>{principle.title}</h3><p>{principle.text}</p></div></div>)}</div></section>
      <section className="contact" id="contact"><div className="container"><div className="contact-grid"><div><div className="eyebrow">03 — {content.contactEyebrow}</div><h2>{content.contactTitle}</h2></div><a className="contact-action" href="mailto:hello@memasevich.ru">{content.contactCta}<span aria-hidden="true">↗</span></a></div><div className="contact-links"><a href="https://github.com/memasevich" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://t.me/memasevich" target="_blank" rel="noopener noreferrer">Telegram ↗</a><a href="https://boosty.to/memasevich" target="_blank" rel="noopener noreferrer">Boosty ↗</a></div></div></section>
    </main><footer className="container footer"><span>© 2026 MEMASEVICH</span><span>{content.footer}</span></footer>
  </div>;
}
